
### Successful test: check response status is 200
GET http://127.0.0.1:8080/api/measurements
Accept: application/json

> {%
client.test("Getting all measurements works", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

### Successful test: check response status is 200
GET http://127.0.0.1:8080/api/measurements/05c6c83f-6697-43be-bf1a-e3b3a297f8d3
Accept: application/json

###

POST http://127.0.0.1:8080/api/measurements/
Content-Type: application/json

{
  "humidity": 1337,
  "carbon_dioxide": 420,
  "temperature": 22.4
}
