
### Successful test: check response status is 200
GET http://127.0.0.1:8080/api/measurements

> {%
client.test("Getting all measurements works", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

### Successful test: check response status is 200
GET http://127.0.0.1:8080/api/measurements/a9a768a0-82b3-11eb-a536-5d7b5228d4ac

> {%
client.test("Getting a specific measurements works", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}