
### Successful test: check response status is 200
GET http://{{$APP_ADDRESS}}:{{$APP_PORT}}/hey

> {%
client.test("Request returns correct text", function() {
  client.assert(response.status === 200, "Response status is not 200");
  client.assert(response.body === 'Hey there!')
});
%}